name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: compile
        env:
          GOOS: js
          GOARCH: wasm
        run: go build -o web/goconway.wasm cmd/main.go
      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          allow_empty_commit: true